1.	Write a Python Program to Add Two Matrices?

In [8]:
arr=[]
n=int(input("Enter N for N X N Matrix : "))
print("Enter the elements : ")

for i in range(n):
  row=[]
  for j in range(n):
    row.append(int(input()))
  arr.append(row)
print(arr)

print("Displaying the array in matrix form : ")
for i in range(n):
  for j in range(n):
    print(arr[i][j], end = " ")
  print()

arr2=[]
n=int(input("Enter N for N X N Matrix : "))
print("Enter the elements : ")

for i in range(n):
  row=[]
  for j in range(n):
    row.append(int(input()))
  arr2.append(row)
print(arr2)

print("Displaying the array in matrix form : ")
for i in range(n):
  for j in range(n):
    print(arr2[i][j], end = " ")
  print()

res = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(n):
  for j in range(len(arr[0])):
    res[i][j]=arr[i][j]+arr2[i][j]

print("Resultant Matrix is : ")
for r in res:
  print(r)

Enter N for N X N Matrix : 3
Enter the elements : 
1
2
3
4
5
6
7
8
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Displaying the array in matrix form : 
1 2 3 
4 5 6 
7 8 9 
Enter N for N X N Matrix : 3
Enter the elements : 
10
20
30
40
50
60
70
80
90
[[10, 20, 30], [40, 50, 60], [70, 80, 90]]
Displaying the array in matrix form : 
10 20 30 
40 50 60 
70 80 90 
Resultant Matrix is : 
[11, 22, 33]
[44, 55, 66]
[77, 88, 99]


2.	Write a Python Program to Multiply Two Matrices?

In [10]:
arr=[]
n=int(input("Enter N for N X N Matrix : "))
print("Enter the elements : ")

for i in range(n):
  row=[]
  for j in range(n):
    row.append(int(input()))
  arr.append(row)
print(arr)

print("Displaying the array in matrix form : ")
for i in range(n):
  for j in range(n):
    print(arr[i][j], end = " ")
  print()

arr2=[]
n=int(input("Enter N for N X N Matrix : "))
print("Enter the elements : ")

for i in range(n):
  row=[]
  for j in range(n):
    row.append(int(input()))
  arr2.append(row)
print(arr2)

print("Displaying the array in matrix form : ")
for i in range(n):
  for j in range(n):
    print(arr2[i][j], end = " ")
  print()
3
res = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(len(arr)):
  for j in range(len(arr2[0])):
    for k in range(len(arr2)):
      res[i][j]+=arr[i][j]*arr2[i][j]

print("Resultant Matrix is : ")
for r in res:
  print(r)

Enter N for N X N Matrix : 3
Enter the elements : 
2
4
6
8
0
1
3
5
7
[[2, 4, 6], [8, 0, 1], [3, 5, 7]]
Displaying the array in matrix form : 
2 4 6 
8 0 1 
3 5 7 
Enter N for N X N Matrix : 3
Enter the elements : 
1
3
5
7
9
2
4
6
8
[[1, 3, 5], [7, 9, 2], [4, 6, 8]]
Displaying the array in matrix form : 
1 3 5 
7 9 2 
4 6 8 
Resultant Matrix is : 
[6, 36, 90]
[168, 0, 6]
[36, 90, 168]


3.	Write a Python Program to Transpose a Matrix?

In [11]:
import numpy
arr=[]
n=int(input("Enter N for N X N Matrix : "))
print("Enter the elements : ")

for i in range(n):
  row=[]
  for j in range(n):
    row.append(int(input()))
  arr.append(row)
print(arr)

print(numpy.transpose(arr))

Enter N for N X N Matrix : 3
Enter the elements : 
1
2
3
4
5
6
7
8
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


4.	Write a Python Program to Sort Words in Alphabetic Order?

In [12]:
str1 = input("Enter a string : ")

words = str1.split()
words.sort()

for word in words:
  print(word)

Enter a string : Myself Karthik and I am working in Infosys as a technology Analyst
Analyst
I
Infosys
Karthik
Myself
a
am
and
as
in
technology
working


5.	Write a Python Program to Remove Punctuation From a String?

In [15]:
samplePunctuations = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''
str1=input("Enter a string : ")
removePunctuations = ""

for char in str1:
  if char not in samplePunctuations:
    removePunctuations=removePunctuations + char
print(removePunctuations)

Enter a string : Hi! I am, karthik !! & I am working as a technology analyst'
Hi I am karthik   I am working as a technology analyst
